ECSSolutions\UblToolset\Structure\V2_1\Common\CommonBasicComponents\EnvironmentalEmissionTypeCode:
    xml_root_name: EnvironmentalEmissionTypeCode
    xml_root_namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
