ECSSolutions\UblToolset\Structure\V2_3\Maindoc\QualificationApplicationResponse\QualificationApplicationResponseType:
    properties:
        uBLExtensions:
            expose: true
            access_type: public_method
            serialized_name: UBLExtensions
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2'
            accessor:
                getter: getUBLExtensions
                setter: setUBLExtensions
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonExtensionComponents\UBLExtension>
            xml_list:
                inline: false
                entry_name: UBLExtension
                skip_when_empty: true
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2'
        uBLVersionID:
            expose: true
            access_type: public_method
            serialized_name: UBLVersionID
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getUBLVersionID
                setter: setUBLVersionID
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\UBLVersionID
        customizationID:
            expose: true
            access_type: public_method
            serialized_name: CustomizationID
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getCustomizationID
                setter: setCustomizationID
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\CustomizationID
        profileID:
            expose: true
            access_type: public_method
            serialized_name: ProfileID
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getProfileID
                setter: setProfileID
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\ProfileID
        profileExecutionID:
            expose: true
            access_type: public_method
            serialized_name: ProfileExecutionID
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getProfileExecutionID
                setter: setProfileExecutionID
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\ProfileExecutionID
        iD:
            expose: true
            access_type: public_method
            serialized_name: ID
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getID
                setter: setID
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\ID
        copyIndicator:
            expose: true
            access_type: public_method
            serialized_name: CopyIndicator
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getCopyIndicator
                setter: setCopyIndicator
            type: bool
        uUID:
            expose: true
            access_type: public_method
            serialized_name: UUID
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getUUID
                setter: setUUID
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\UUID
        contractFolderID:
            expose: true
            access_type: public_method
            serialized_name: ContractFolderID
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getContractFolderID
                setter: setContractFolderID
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\ContractFolderID
        contractName:
            expose: true
            access_type: public_method
            serialized_name: ContractName
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getContractName
                setter: setContractName
            xml_list:
                inline: true
                entry_name: ContractName
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\ContractName>
        issueDate:
            expose: true
            access_type: public_method
            serialized_name: IssueDate
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getIssueDate
                setter: setIssueDate
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Date
        issueTime:
            expose: true
            access_type: public_method
            serialized_name: IssueTime
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getIssueTime
                setter: setIssueTime
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Time
        economicOperatorGroupName:
            expose: true
            access_type: public_method
            serialized_name: EconomicOperatorGroupName
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getEconomicOperatorGroupName
                setter: setEconomicOperatorGroupName
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\EconomicOperatorGroupName
        versionID:
            expose: true
            access_type: public_method
            serialized_name: VersionID
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getVersionID
                setter: setVersionID
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\VersionID
        previousVersionID:
            expose: true
            access_type: public_method
            serialized_name: PreviousVersionID
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getPreviousVersionID
                setter: setPreviousVersionID
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\PreviousVersionID
        procedureCode:
            expose: true
            access_type: public_method
            serialized_name: ProcedureCode
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getProcedureCode
                setter: setProcedureCode
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\ProcedureCode
        qualificationApplicationTypeCode:
            expose: true
            access_type: public_method
            serialized_name: QualificationApplicationTypeCode
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getQualificationApplicationTypeCode
                setter: setQualificationApplicationTypeCode
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\QualificationApplicationTypeCode
        weightScoringMethodologyNote:
            expose: true
            access_type: public_method
            serialized_name: WeightScoringMethodologyNote
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getWeightScoringMethodologyNote
                setter: setWeightScoringMethodologyNote
            xml_list:
                inline: true
                entry_name: WeightScoringMethodologyNote
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\WeightScoringMethodologyNote>
        weightingTypeCode:
            expose: true
            access_type: public_method
            serialized_name: WeightingTypeCode
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getWeightingTypeCode
                setter: setWeightingTypeCode
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\WeightingTypeCode
        note:
            expose: true
            access_type: public_method
            serialized_name: Note
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getNote
                setter: setNote
            xml_list:
                inline: true
                entry_name: Note
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\Note>
        contractingParty:
            expose: true
            access_type: public_method
            serialized_name: ContractingParty
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getContractingParty
                setter: setContractingParty
            xml_list:
                inline: true
                entry_name: ContractingParty
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonAggregateComponents\ContractingParty>
        economicOperatorParty:
            expose: true
            access_type: public_method
            serialized_name: EconomicOperatorParty
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getEconomicOperatorParty
                setter: setEconomicOperatorParty
            xml_list:
                inline: true
                entry_name: EconomicOperatorParty
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonAggregateComponents\EconomicOperatorParty>
        procurementProject:
            expose: true
            access_type: public_method
            serialized_name: ProcurementProject
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getProcurementProject
                setter: setProcurementProject
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonAggregateComponents\ProcurementProject
        procurementProjectLot:
            expose: true
            access_type: public_method
            serialized_name: ProcurementProjectLot
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getProcurementProjectLot
                setter: setProcurementProjectLot
            xml_list:
                inline: true
                entry_name: ProcurementProjectLot
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonAggregateComponents\ProcurementProjectLot>
        tenderingCriterion:
            expose: true
            access_type: public_method
            serialized_name: TenderingCriterion
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getTenderingCriterion
                setter: setTenderingCriterion
            xml_list:
                inline: true
                entry_name: TenderingCriterion
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonAggregateComponents\TenderingCriterion>
        tenderingCriterionResponse:
            expose: true
            access_type: public_method
            serialized_name: TenderingCriterionResponse
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getTenderingCriterionResponse
                setter: setTenderingCriterionResponse
            xml_list:
                inline: true
                entry_name: TenderingCriterionResponse
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonAggregateComponents\TenderingCriterionResponse>
        additionalDocumentReference:
            expose: true
            access_type: public_method
            serialized_name: AdditionalDocumentReference
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getAdditionalDocumentReference
                setter: setAdditionalDocumentReference
            xml_list:
                inline: true
                entry_name: AdditionalDocumentReference
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonAggregateComponents\AdditionalDocumentReference>
        evidence:
            expose: true
            access_type: public_method
            serialized_name: Evidence
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getEvidence
                setter: setEvidence
            xml_list:
                inline: true
                entry_name: Evidence
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonAggregateComponents\Evidence>
        signature:
            expose: true
            access_type: public_method
            serialized_name: Signature
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getSignature
                setter: setSignature
            xml_list:
                inline: true
                entry_name: Signature
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonAggregateComponents\Signature>
