ECSSolutions\UblToolset\Structure\V2_3\Maindoc\QualificationApplicationRequest\QualificationApplicationRequest:
    xml_root_name: QualificationApplicationRequest
    xml_root_namespace: 'urn:oasis:names:specification:ubl:schema:xsd:QualificationApplicationRequest-2'
