ECSSolutions\UblToolset\Structure\V2_3\Maindoc\ApplicationResponse\ApplicationResponse:
    xml_root_name: ApplicationResponse
    xml_root_namespace: 'urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2'
