ECSSolutions\UblToolset\Structure\V2_3\Common\CommonAggregateComponents\EnvironmentalEmissionType:
    properties:
        uBLExtensions:
            expose: true
            access_type: public_method
            serialized_name: UBLExtensions
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2'
            accessor:
                getter: getUBLExtensions
                setter: setUBLExtensions
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonExtensionComponents\UBLExtension>
            xml_list:
                inline: false
                entry_name: UBLExtension
                skip_when_empty: true
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2'
        environmentalEmissionTypeCode:
            expose: true
            access_type: public_method
            serialized_name: EnvironmentalEmissionTypeCode
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getEnvironmentalEmissionTypeCode
                setter: setEnvironmentalEmissionTypeCode
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\EnvironmentalEmissionTypeCode
        valueMeasure:
            expose: true
            access_type: public_method
            serialized_name: ValueMeasure
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getValueMeasure
                setter: setValueMeasure
            type: ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\ValueMeasure
        description:
            expose: true
            access_type: public_method
            serialized_name: Description
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getDescription
                setter: setDescription
            xml_list:
                inline: true
                entry_name: Description
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\Description>
        emissionCalculationMethod:
            expose: true
            access_type: public_method
            serialized_name: EmissionCalculationMethod
            xml_element:
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getEmissionCalculationMethod
                setter: setEmissionCalculationMethod
            xml_list:
                inline: true
                entry_name: EmissionCalculationMethod
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<ECSSolutions\UblToolset\Structure\V2_3\Common\CommonAggregateComponents\EmissionCalculationMethod>
