ECSSolutions\UblToolset\Structure\V2_3\Common\CommonBasicComponents\ShipConfigurationCode:
    xml_root_name: ShipConfigurationCode
    xml_root_namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
