ECSSolutions\UblToolset\Structure\V2_3\Maindoc\QualificationApplicationResponse\QualificationApplicationResponse:
    xml_root_name: QualificationApplicationResponse
    xml_root_namespace: 'urn:oasis:names:specification:ubl:schema:xsd:QualificationApplicationResponse-2'
